import { useEffect, useState } from "react";
import { ArrowUpRight, BedDouble, Bath, Users, Wifi, Wind, CookingPot, Trees, Car, Flame, Tv, Utensils, MapPin, Check, ChevronLeft, ChevronRight, Plus } from "lucide-react";
import { bookingUrl } from "@/property-data";
import { destinations, feedback, policies, estateAmenities } from "./stay-content";
import { PropertyGallery } from "./property-gallery";
import "./home-details.css";

const roomChoices = [
 {name:"The main bedroom",detail:"King bed · En-suite bathroom",image:"main-bedroom",body:"A generous room beneath the thatch, with a king bed and its own bathroom. A quiet retreat before another early start."},
 {name:"The queen bedroom",detail:"Queen bed · Sleeps two",image:"queen",body:"A comfortable space for a second couple or adult guests, with easy bathroom access and room to settle in."},
 {name:"The twin bedroom",detail:"Two single beds · Sleeps two",image:"twin",body:"A room for siblings, friends and little adventurers. Separate beds give everyone their own place to recharge."},
];
const estateViews = [
 {name:"Golf & open spaces",image:"estate",title:"Take the scenic route.",body:"A nine-hole golf course, established gardens and space to wander. There is plenty to enjoy right on the estate."},
 {name:"A quieter moment",image:"pool",title:"Let the day slow down.",body:"Find a peaceful spot overlooking the water, then make time for the estate pools, tennis or a family afternoon outdoors."},
 {name:"Dining & leisure",image:"estate2",title:"Everything, a little closer.",body:"A restaurant and bar, children’s play area, mini golf and 24-hour reception make an easy base for your Lowveld stay."},
];
const amenities = [[Wifi,"Free Wi-Fi"],[Wind,"Air conditioning"],[CookingPot,"Full kitchen"],[Tv,"Smart TV"],[Car,"Parking"],[Flame,"Private braai"],[Utensils,"Dining space"],[Trees,"Private patio"]] as const;
const jumpLinks=[["explore","Overview"],["rooms","Rooms"],["facilities","The estate"],["location","Explore"],["reviews","Reviews"],["policies","Good to know"]];
function StayNavigation(){
 const [active,setActive]=useState("explore");
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(entry.target.id)},{rootMargin:"-15% 0px -55% 0px"});for(const [id] of jumpLinks){const el=document.getElementById(id);if(el)observer.observe(el)}return()=>observer.disconnect()},[]);
 return <nav className="stay-navigation" aria-label="Explore your stay"><div>{jumpLinks.map(([id,label])=><a key={id} href={`#${id}`} aria-current={active===id?"location":undefined}>{label}</a>)}</div><a href="#booking" className="stay-nav-book">Plan your stay <ArrowUpRight size={15}/></a></nav>
}
function BookingPlanner(){
 const [arrival,setArrival]=useState("");const [departure,setDeparture]=useState("");const [guests,setGuests]=useState("2");
 const [today,setToday]=useState("");
 useEffect(()=>{const d=new Date();setToday(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`)},[]);
 const minimumDeparture=arrival?new Date(Date.parse(arrival)+86400000).toISOString().slice(0,10):today;
 const nights=arrival&&departure?Math.round((Date.parse(departure)-Date.parse(arrival))/86400000):0;
 return <section id="booking" className="home-booking"><img src="/assets/stay/patio.jpg" alt="Outdoor dining on the private patio" loading="lazy"/><div className="home-booking-content"><span className="home-eyebrow">Your next chapter</span><h2>A few days away.<br/>A little closer together.</h2><p>Choose your dates. Make House 225B your own.</p><form action={bookingUrl} method="get" target="_blank"><label>Check-in<input type="date" name="checkin" required min={today} value={arrival} onChange={e=>{setArrival(e.target.value);if(departure<=e.target.value)setDeparture("")}}/></label><label>Check-out<input type="date" name="checkout" required min={minimumDeparture} value={departure} onChange={e=>setDeparture(e.target.value)}/></label><label>Adults<select name="adults" value={guests} onChange={e=>setGuests(e.target.value)}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} {n===1?"adult":"adults"}</option>)}</select></label><button className="home-button" type="submit">Check availability <ArrowUpRight size={17}/></button></form><p className="booking-note" aria-live="polite">{nights>0?`${nights} nights · `:""}Live rates on NightsBridge. Add children and their ages when booking. Maximum six guests.</p></div></section>
}
export function HomeDetails(){
 const [room,setRoom]=useState(0);const [estate,setEstate]=useState(0);const [review,setReview]=useState(0);const [filter,setFilter]=useState("Nature & safari");
 const groups:Record<string,number[]>={"Nature & safari":[0,1,2,3,4,10],"Leisure":[6,8],"Getting around":[5,7,9]};
 const chosen=roomChoices[room];const view=estateViews[estate];const guest=feedback[review];
 return <div className="home-details" id="stay">
 <StayNavigation/>
 <section className="home-section home-intro" id="explore" tabIndex={-1} aria-labelledby="overview-title"><div><span className="home-eyebrow">House 225B · Kruger Park Lodge</span><h2 id="overview-title">Your own little<br/>piece of the Lowveld.</h2></div><div className="intro-copy"><p>A private home beneath the trees. Long lunches on the deck. Early starts for the wild.</p><p>Settle into a three-bedroom self-catering stay in Hazyview, with the freedom of your own space and the comforts of Kruger Park Lodge Estate.</p><a className="home-text-link" href="#rooms">Come on in <ArrowUpRight size={17}/></a></div><dl className="home-facts">{[[Users,"6","Guests"],[BedDouble,"3","Bedrooms"],[Bath,"3","Bathrooms"],[Trees,"Your own","Patio & braai"]].map(([Icon,value,label])=>{const FactIcon=Icon as typeof Users;return <div key={String(label)}><FactIcon size={24} strokeWidth={1.2}/><dd>{String(value)}</dd><dt>{String(label)}</dt></div>})}</dl></section>
 <PropertyGallery/>
 <section className="home-section" id="rooms" aria-labelledby="rooms-title"><div className="home-section-heading"><div><span className="home-eyebrow">01 / Your rooms</span><h2 id="rooms-title">Room for everyone.<br/>Space for yourself.</h2></div><p>Three bedrooms. Three bathrooms.<br/>One place to come back to.</p></div><div className="room-story"><div className="room-story-image"><img key={chosen.image} src={`/assets/stay/${chosen.image}.jpg`} srcSet={`/assets/stay/${chosen.image}-800.jpg 800w, /assets/stay/${chosen.image}.jpg 1600w`} sizes="(max-width:700px) 100vw, 55vw" alt={chosen.name+" at House 225B"} width="1600" height="1065" loading="lazy"/><span>0{room+1} / 03</span></div><div className="room-story-options">{roomChoices.map((item,index)=><div className="room-story-item" key={item.name}><button type="button" aria-expanded={room===index} aria-controls={`room-description-${index}`} onClick={()=>setRoom(index)}><span className="room-index">0{index+1}</span><span>{item.name}<small>{item.detail}</small></span><Plus size={19} className={room===index?"is-open":""}/></button><div id={`room-description-${index}`} hidden={room!==index}><p>{item.body}</p></div></div>)}<a className="home-text-link" href="#booking">Find your dates <ArrowUpRight size={17}/></a></div></div><div className="home-amenities">{amenities.map(([Icon,label])=><div key={label}><Icon size={21} strokeWidth={1.3}/><span>{label}</span></div>)}</div></section>
 <section className="home-estate" id="facilities" aria-labelledby="estate-title"><div className="home-section"><div className="home-section-heading"><div><span className="home-eyebrow">02 / Life on the estate</span><h2 id="estate-title">Some days,<br/>stay a little closer.</h2></div><p>Golf, gardens and afternoons with nowhere to rush. Your holiday continues beyond the front door.</p></div><div className="estate-tabs" role="group" aria-label="Explore the estate">{estateViews.map((item,index)=><button key={item.name} type="button" aria-pressed={estate===index} onClick={()=>setEstate(index)}>{item.name}</button>)}</div><div className="estate-story"><img key={view.image} src={`/assets/stay/${view.image}.jpg`} alt={view.name+" at Kruger Park Lodge"} width="1024" height="683" loading="lazy"/><div key={view.name} className="estate-caption" aria-live="polite"><h3>{view.title}</h3><p>{view.body}</p></div></div><div className="estate-features">{estateAmenities.map(item=><span key={item}><Check size={15}/>{item}</span>)}</div></div></section>
 <section className="home-section" id="location" aria-labelledby="location-title"><div className="home-section-heading"><div><span className="home-eyebrow">03 / Beyond the lodge</span><h2 id="location-title">Start here.<br/>Go somewhere wonderful.</h2></div><div><p>Hazyview puts safari days, scenic drives and everyday essentials within reach.</p><a className="home-text-link" href="https://www.google.com/maps/search/?api=1&query=Kruger+Park+Lodge+Hazyview" target="_blank" rel="noopener noreferrer"><MapPin size={16}/> Find House 225B</a></div></div><div className="local-explorer"><aside><span className="home-eyebrow">Make a day of it</span>{Object.keys(groups).map(name=><button type="button" key={name} aria-pressed={filter===name} onClick={()=>setFilter(name)}>{name}<ArrowUpRight size={16}/></button>)}<p>Kruger Park Lodge Estate<br/>Portia Shabangu Road<br/>Hazyview, Mpumalanga 1242<br/>South Africa</p></aside><div className="local-list" aria-live="polite">{destinations.filter((_,index)=>groups[filter].includes(index)).map(([name,distance,description])=><details key={name}><summary><span>{name}<small>{distance}</small></span><Plus size={18}/></summary><p>{description}</p><a className="home-text-link" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(name+" South Africa")} target="_blank" rel="noopener noreferrer">Explore on Maps <ArrowUpRight size={15}/></a></details>)}</div></div><p className="home-note">Distances are approximate. Allow for road conditions, traffic and safari gate queues.</p></section>
 <section className="home-reviews" id="reviews" aria-labelledby="reviews-title"><div className="home-section review-layout"><div><span className="home-eyebrow">04 / In their words</span><h2 id="reviews-title">Guest reviews.<br/>Lasting impressions.</h2><p>What guests remember about House 225B and Kruger Park Lodge.</p><div className="review-controls"><button type="button" aria-label="Previous guest review" onClick={()=>setReview((review+feedback.length-1)%feedback.length)}><ChevronLeft size={20}/></button><span>{String(review+1).padStart(2,"0")} / {String(feedback.length).padStart(2,"0")}</span><button type="button" aria-label="Next guest review" onClick={()=>setReview((review+1)%feedback.length)}><ChevronRight size={20}/></button></div></div><article className="featured-review" aria-live="polite"><span className="review-symbol" aria-hidden="true">“</span><span className="review-type">Guest review · Summary</span><p key={guest[0]} className="review-words">{guest[2]}</p><div className="review-author"><span className="review-avatar" aria-hidden="true">{guest[0].slice(0,1)}</span><div><strong>{guest[0]}</strong><span>{guest[1]}</span></div></div><div className="review-dots">{feedback.map(([name],index)=><button key={name} type="button" aria-label={`Read ${name}’s review summary`} aria-pressed={review===index} onClick={()=>setReview(index)}/>)}</div></article><details className="review-source"><summary>About these reviews</summary><p>Summaries of feedback published by Kruger Vacations about the property and estate. The original site lists an overall score of 8.8, location 8.7, comfort 8.5, cleanliness 8.4 and facilities 8.2, without platform or date verification. Its homepage also includes a Johnson Family testimonial with five-star displays. These are not independently verified ratings.</p><a href="https://www.krugervacations.co.za/reviews.html" target="_blank" rel="noopener noreferrer">View the original guest feedback ↗</a></details></div></section>
 <section className="home-section home-practical" id="policies" aria-labelledby="practical-title"><div><span className="home-eyebrow">05 / Good to know</span><h2 id="practical-title">Arrive with<br/>the details sorted.</h2><div className="arrival-times"><div><span>Check-in</span><strong>16:00–21:00</strong></div><div><span>Check-out</span><strong>06:00–10:00</strong></div></div><p>Let us know when you’ll arrive.<br/>We’ll help with the rest.</p><a className="home-text-link" href="#contact">Ask a question <ArrowUpRight size={16}/></a></div><div className="home-policy-list">{policies.map(([title,body])=><details key={title}><summary>{title}<Plus size={17}/></summary><p>{body}</p></details>)}</div></section>
 <BookingPlanner/>
 <section className="home-section home-contact" id="contact"><div><span className="home-eyebrow">A little help planning?</span><h2>Let’s talk about your stay.</h2><p>Family trips, longer stays or special requests — get in touch.</p></div><div><a href="mailto:info@krugervacations.co.za">info@krugervacations.co.za <ArrowUpRight size={17}/></a><a href="tel:+27718994063">+27 71 899 4063 <ArrowUpRight size={17}/></a><a href="https://www.krugervacations.co.za/book.html" target="_blank" rel="noopener noreferrer">Send a direct booking enquiry <ArrowUpRight size={17}/></a><p>Include your dates, guest numbers and children’s ages. An enquiry is not a confirmed reservation.</p></div></section>
 </div>
}
